import {TrpcProvider} from "@/app/TrpcProvider";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// here we wrap all of our pages with TrpcProvider to enable the client to invoke RPCs

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <TrpcProvider>
        <html lang="en">
            <head></head>
            <body>
                {children}
            </body>
        </html>
      </TrpcProvider>
  )
}
